=== Tshah28/WellArchitected-Assessment/schema/github.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://waf/1.0/github.schema.json",
  
  "title": "AssessmentItem",
  "description": "Single item within an assessment. Can be a question, recommendation, consideration etc.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": ""
    },
    "type": {
      "type": "string",
      "description": "",
      "enum": [
        "Questions",
        "Design Principles",
        "Design Considerations",
        "Design Recommendations",
        "Configuration Recommendations",
        "Supporting Source Artifacts"
      ]
    },
    "pillars": {
      "type": "array",
      "description": "",
      "items": {
        "anyOf": [
          {
            "type": "string",
            "description": "WAF pillar into which this item belongs.",
            "enum": [
              "costoptimization",
              "golive",
              "operationalexcellence",
              "performanceefficiency",
              "reliability",
              "security"
            ],
            "examples": [ "costoptimization" ]
          }
        ]
      }
    },
    "lens": {
      "type": "string",
      "description": ""
    },
    "category": {
      "type": "string",
      "description": ""
    },
    "subCategory": {
      "type": "string",
      "description": ""
    },
    "title": {
      "type": "string",
      "description": ""
    },
    "context": {
      "type": "string",
      "description": ""
    },
    "recommendation": {
      "type": "string",
      "description": ""
    }
  },
  "required": [ "id" ]
}

=== Tshah28/WellArchitected-Assessment/data/servicelens-hybrid.data.json
[
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability",
      "operationalexcellence"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Microsoft does not provide an SLA for Azure Stack Hub because Microsoft does not have control over customer datacenter reliability, people, and processes.",
    "id": "6028ceae-8207-4601-b30d-ff3ee045a1bb"
  },
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability",
      "operationalexcellence"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Azure Stack Hub currently only supports a single Scale Unit (SU) within in a single Region, which can consist of between 4 and 16 servers that use Hyper-V failover clustering; each region serves as an independent Azure Stack Hub \"stamp\" with separate portal and API endpoints.",
    "context": "Azure Stack Hub does therefore **not support Availability Zones** as it currently consists only of a single \"region\" (aka a single physical location). High availability to cope with outages of a single location should be implemented by using two Azure Stack Hub instances deployed into different physical locations.",
    "id": "562dba61-e2c1-4623-8a91-752cc2baaf68"
  },
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Azure Stack Hub supports **Premium Storage** to ensure compatibility, however, provisioning premium storage accounts or disks does not guarantee that storage objects will be allocated onto SSD or NVMe drives.",
    "id": "08b38927-f2ba-49ab-a44b-7e02eeafae5d"
  },
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Azure Stack Hub supports only a subset of [VPN Gateway SKUs](https://docs.microsoft.com/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways#estimated-aggregate-throughput-by-sku) available in Azure with a limited bandwidth of 100 or 200 Mbps.",
    "context": "Only one site-to-site (S2S) VPN connection can be created between two Azure Stack Hub deployments. This is due to a limitation in the platform that only allows a single VPN connection to the same IP address. Multiple S2S VPN connections with higher throughput can be established using 3rd-party NVAs.",
    "id": "8997a0d8-ffdc-48cf-9fd0-c94e621907a4"
  },
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Azure Stack Hub does currently not support [Virtual network peering](https://docs.microsoft.com/azure/virtual-network/virtual-network-peering-overview).",
    "context": "Two networks (on the same Azure Stack Hub \"stamp\") can also not be connected via Azure (Stack) VPN GWs as they're sharing the same IP address. Virtual networks on Azure Stack Hub can be connected using 3rd-party NVAs (e.g. [Fortinet Fortigate](https://docs.microsoft.com/azure-stack/user/azure-stack-network-howto-vnet-to-vnet?view=azs-2002)).",
    "id": "0132f288-b0b7-44f7-9dce-e524eb667bb6"
  },
  {
    "type": "Configuration Recommendations",
    "pillars": [
      "reliability",
      "operationalexcellence"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Treat Azure Stack Hub as a scale unit and deploy multiple instances to remove Azure Stack Hub as a single point of failure for encompassed workloads.",
    "children": [
      {
        "title": "Deploy workloads in either an active-active or active-passive configuration across Azure Stack Hub stamps and/or Azure.",
        "id": "b33d34ba-e9be-4011-88c8-d75f5d16de40"
      }
    ],
    "id": "7bce53c8-3617-416f-bfb8-2abeb0cf068d"
  },
  {
    "type": "Design Considerations",
    "pillars": [
      "reliability",
      "operationalexcellence"
    ],
    "lens": "service",
    "category": "Hybrid",
    "subCategory": "Azure Stack Hub",
    "title": "Apply general Azure configuration recommendations for all Azure Stack Hub services.",
    "id": "e26f72b8-f176-44e7-aa38-2c7366ed0f9f"
  }
]

=== Tshah28/WellArchitected-Assessment/data/designprinciples.data.json
[
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Optimize build and release processes",
        "context": "From provisioning with Infrastructure as Code, to build and releases with CI/CD pipelines, to automated testing, embrace software engineering discipline across your entire environment. This approach ensures the creation and management of environments throughout the software development lifecycle is consistent and enables early detection of issues.",
        "id": "dp_opex_1"
    },
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Monitor system and operational health",
        "context": "Identify and monitor metrics for build and release processes, infrastructure health, and application health. Telemetry is critical to understanding the health of a workload and whether the service is meeting the business goals.",
        "id": "dp_opex_2"
    },
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Rehearse recovery and practice failure",
        "context": "Run DR drills on regular cadence and use chaos engineering practices to identify and remediate weak points in application reliability. Regular rehearsal of failure will validate the effectiveness of recovery processes and ensure teams are familiar with their responsibilities.",
        "id": "dp_opex_3"
    },
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Modularize your environment",
        "context": "Systematically componentize your environment and workloads to enable frequent and manageable change that can be progressively rolled-out and safely rolled-back.",
        "id": "dp_opex_4"
    },
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Use policy-driven governance",
        "context": "Use Azure Policy to provide guardrails and ensure continued compliance of application environment. This approach to centralized governance enables an organization to provide application teams with sufficient autonomy to accelerate development efforts, while ensuring the enterprise estate remains compliant with organizational standards.",
        "id": "dp_opex_5"
    },
    {
        "type": "Design Principles",
        "pillars": [
            "operationalexcellence"
        ],
        "lens": "application",
        "category": "General",
        "subCategory": "Unassigned",
        "title": "Embrace operational improvement",
        "context": "Continuously evaluate and refine operational procedures and tasks, while striving to reduce complexity and ambiguity. This approach enables an organization to evolve processes over time, optimizing inefficiencies and learning from failures.",
        "id": "dp_opex_6"
    }
]
